# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bandara.S.N.M.C-Cobsccomp171p-036' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bandara.S.N.M.C-Cobsccomp171p-036

  target 'Bandara.S.N.M.C-Cobsccomp171p-036Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bandara.S.N.M.C-Cobsccomp171p-036UITests' do
    inherit! :search_paths
    # Pods for testing
  end

	pod 'Firebase/Analytics'
	pod 'GoogleSignIn'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'	
	pod 'Firebase/Firestore'	
	pod 'Firebase/Core'
	pod 'SwiftyJSON'
	pod 'Firebase/Storage'
	pod 'Alamofire', '~>4.4'
	pod 'Kingfisher', '~> 4.0'
	pod 'IQKeyboardManagerSwift'	

end
